// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh6oDt2yjj6KBEggiQGFhMtg8WlSuW5a4',
    appId: '1:415654659389:web:2024867c1760dfe854f154',
    messagingSenderId: '415654659389',
    projectId: 'odbayar01',
    authDomain: 'odbayar01.firebaseapp.com',
    storageBucket: 'odbayar01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK3kOYvqSoIJ9UYZqo9ikEt69zeET0JrU',
    appId: '1:415654659389:android:b06c3db5da83366854f154',
    messagingSenderId: '415654659389',
    projectId: 'odbayar01',
    storageBucket: 'odbayar01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXC1-zqUrQ1Wai6mDko3vTZfQpJ5iSydE',
    appId: '1:415654659389:ios:f63e43f773a96df054f154',
    messagingSenderId: '415654659389',
    projectId: 'odbayar01',
    storageBucket: 'odbayar01.firebasestorage.app',
    iosBundleId: 'com.example.spotipyt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXC1-zqUrQ1Wai6mDko3vTZfQpJ5iSydE',
    appId: '1:415654659389:ios:f63e43f773a96df054f154',
    messagingSenderId: '415654659389',
    projectId: 'odbayar01',
    storageBucket: 'odbayar01.firebasestorage.app',
    iosBundleId: 'com.example.spotipyt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh6oDt2yjj6KBEggiQGFhMtg8WlSuW5a4',
    appId: '1:415654659389:web:25193004340a00e854f154',
    messagingSenderId: '415654659389',
    projectId: 'odbayar01',
    authDomain: 'odbayar01.firebaseapp.com',
    storageBucket: 'odbayar01.firebasestorage.app',
  );
}
